apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: open5gs
spec:
  selector:
    app: amf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: ngap
      protocol: SCTP
      port: 38412
      targetPort: 38412
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: local/open5gs:latest
        imagePullPolicy: Never
        command: ["/bin/open5gs-amfd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/amf.yaml"]
        ports:
        - containerPort: 7777
          name: sbi
        - containerPort: 38412
          name: ngap
          protocol: SCTP
        volumeMounts:
        - name: amf-config
          mountPath: /opt/open5gs/etc/open5gs
      volumes:
      - name: amf-config
        configMap:
          name: amf-config
