apiVersion: v1
kind: Service
metadata:
  name: ausf
  namespace: open5gs
spec:
  selector:
    app: ausf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
      - name: ausf
        image: local/open5gs:latest
        imagePullPolicy: Never
        command: ["/bin/open5gs-ausfd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/ausf.yaml"]
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: ausf-config
          mountPath: /opt/open5gs/etc/open5gs
      volumes:
      - name: ausf-config
        configMap:
          name: ausf-config
