apiVersion: v1
kind: Service
metadata:
  name: bsf
  namespace: open5gs
spec:
  selector:
    app: bsf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsf
  template:
    metadata:
      labels:
        app: bsf
    spec:
      containers:
      - name: bsf
        image: local/open5gs:latest
        imagePullPolicy: Never
        command: ["/bin/open5gs-bsfd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/bsf.yaml"]
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: bsf-config
          mountPath: /opt/open5gs/etc/open5gs
      volumes:
      - name: bsf-config
        configMap:
          name: bsf-config
