apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config
  namespace: open5gs
data:
  pcf.yaml: |
    logger:
      level: info

    global:
      max:
        ue: 1024

    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: pcf.open5gs.svc.cluster.local
        client:
          nrf:
            - uri: http://nrf:7777

    db_uri: mongodb://mongodb:27017/open5gs
