apiVersion: v1
kind: ConfigMap
metadata:
  name: scp-config
  namespace: open5gs
data:
  scp.yaml: |
    logger:
      level: info

    global:
      max:
        ue: 1024

    scp:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://nrf:7777
      discovery:
        option: auto
