apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-config
  namespace: open5gs
data:
  nssf.yaml: |
    logger:
      level: info

    global:
      max:
        ue: 1024

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: nssf.open5gs.svc.cluster.local
        client:
          nrf:
            - uri: http://nrf:7777
          nsi:
            - uri: http://nsi:7777
              s_nssai:
                sst: 1
