apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: open5gs
data:
  ausf.yaml: |
    logger:
      level: info

    global:
      max:
        ue: 1024

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: ausf.open5gs.svc.cluster.local
        client:
          nrf:
            - uri: http://nrf:7777
