apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: open5gs
data:
  nrf.yaml: |
    logger:
      level: info

    global:
      max:
        ue: 1024

    nrf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
      service_name:
        - nnrf-nfm
        - nnrf-disc
