apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-config
  namespace: open5gs
data:
  bsf.yaml: |
    logger:
      level: info

    global:
      max:
        ue: 1024

    bsf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise: bsf.open5gs.svc.cluster.local
        client:
          nrf:
            - uri: http://nrf:7777
