apiVersion: v1
kind: Service
metadata:
  name: pcf
  namespace: open5gs
spec:
  selector:
    app: pcf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
    spec:
      containers:
      - name: pcf
        image: local/open5gs:latest
        imagePullPolicy: Never
        command: ["/bin/open5gs-pcfd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/pcf.yaml"]
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: pcf-config
          mountPath: /opt/open5gs/etc/open5gs
      volumes:
      - name: pcf-config
        configMap:
          name: pcf-config
