apiVersion: v1
kind: Service
metadata:
  name: scp
  namespace: open5gs
spec:
  selector:
    app: scp
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scp
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scp
  template:
    metadata:
      labels:
        app: scp
    spec:
      containers:
      - name: scp
        image: local/open5gs:latest
        imagePullPolicy: Never
        command: ["/bin/open5gs-scpd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/scp.yaml"]
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: scp-config
          mountPath: /opt/open5gs/etc/open5gs
      volumes:
      - name: scp-config
        configMap:
          name: scp-config
