apiVersion: v1
kind: Service
metadata:
  name: udr
  namespace: open5gs
spec:
  selector:
    app: udr
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:
      - name: udr
        image: local/open5gs:latest
        imagePullPolicy: Never
        command: ["/bin/open5gs-udrd"]
        args: ["-c", "/opt/open5gs/etc/open5gs/udr.yaml"]
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: udr-config
          mountPath: /opt/open5gs/etc/open5gs
      volumes:
      - name: udr-config
        configMap:
          name: udr-config
