apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-config
  namespace: open5gs
data:
  open5gs-gnb.yaml: |
    mcc: '999'
    mnc: '70'

    nci: '0x000000010'
    idLength: 32
    tac: 1

    linkIp: 0.0.0.0
    ngapIp: 0.0.0.0
    gtpIp: 0.0.0.0

    amfConfigs:
      - address: amf
        port: 38412

    slices:
      - sst: 1

    ignoreStreamIds: true
